id: P000518
initial_creation_type: ocr
source_metadata:
  id: bdr:W21743
  title: གནའ་གཏམ་མཐོང་བ་དགའ་སྐྱེད
  author: ''
  volumes:
    2462df8e8a2f4d89814bbca649eb1501:
      image_group_id: I1KG12584
      title: Volume 1 of mdo mang /
      volume_number: 1
      total_pages: 756
    42ce8b9b838f4a3ebf4f49d3ed8e3a52:
      image_group_id: I1KG12588
      title: ''
      volume_number: 2
      total_pages: 756
ebook_metadata:
  title: གནའ་གཏམ་མཐོང་བ་དགའ་སྐྱེད
  author: ''
  sku: P000518
  cover: cover.jpg
  layers:
  - pagination
